#!/bin/bash

SAMPLE=$1
MOCK=$2
PIPELINE=$3
IDENTIFIER=$4
TRIM=$5
MERGECONCAT=$6
DADA2PROC=$7
REGION=$8
PRIMERSET=$9
MOCKTYPE=${10}
STUDY=${11}

cd /Mocks/$MOCK

echo "$SAMPLE	$MOCK	$PIPELINE	$TRIM	$MERGECONCAT	$DADA2PROC	$REGION	$PRIMERSET	$MOCKTYPE	$STUDY" >> Metadata_$MOCK.$PIPELINE.txt
echo "$SAMPLE	$MOCK	$PIPELINE	${IDENTIFIER}.G	$TRIM	$MERGECONCAT	$DADA2PROC	$REGION	$PRIMERSET	$MOCKTYPE	$STUDY	GG" >> Metadata_$MOCK.$PIPELINE.GG.txt
echo "$SAMPLE	$MOCK	$PIPELINE	${IDENTIFIER}.S	$TRIM	$MERGECONCAT	$DADA2PROC	$REGION	$PRIMERSET	$MOCKTYPE	$STUDY	SILVA" >> Metadata_$MOCK.$PIPELINE.SILVA.txt

cd /Mocks